### ISSUE TITLE
[HW] <Ashish Pawar>

### ISSUE THREAD

**Issue by ampawar30** [datastaxdevs/workshop-intro-to-graphql#49]
**Name:** Ashish Pawar
**Email:** amp30497@gmail.com
**Linkedin Profile:** https://in.linkedin.com/in/ashish-pawar-9bb478131

Attach the homework screenshot below:
-----------------------------------------

<SCREENSHOT>
![Screenshot from 2021-09-16 01-52-24](https://user-images.githubusercontent.com/31410028/133504589-73318eb8-537d-4405-a942-ae854647efa0.png)
![Screenshot from 2021-09-16 01-51-02](https://user-images.githubusercontent.com/31410028/133504591-d5f0ff39-83ae-498d-b119-300412c0c132.png)
![Screenshot from 2021-09-16 01-52-24](https://user-images.githubusercontent.com/31410028/133504699-cf658234-a9e9-49f2-a974-d4b34b2b527f.png)

**Comment by HadesArchitect** [comment]
Hey **Ashish Pawar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Cu4LmFnnSY21Kqb4elKLRg

**Comment by ampawar30** [comment]
Thank you
