### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by juliann** [datastaxdevs/workshop-intro-to-graphql#5]
**Name:** Julian Nadarzy
**Email:** : julian.nadarzy@gmail.com
**Linkedin Profile:**  https://www.linkedin.com/in/julian-nadarzy-74b7b810
Attach the homework screenshot below:
-----------------------------------------

![astra1](https://user-images.githubusercontent.com/1125748/133482355-7f8221c3-1c52-439e-a16f-41c53a09683f.jpg)

**Comment by RyanWelford** [comment]
Good show choice! ;) Well done!

**Comment by HadesArchitect** [comment]
Hey **Julian Nadarzy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/e5IVsZiFQnOJBi2TNvIM1w
