### ISSUE TITLE
[HW] Bhaskar Pal

### ISSUE THREAD

**Issue by pal-bhaskar** [datastaxdevs/workshop-intro-to-graphql#61]
**Name:** Bhaskar Pal
**Email:** bhaskarpaal@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/bhaskar-pal-3364758a/

Attach the homework screenshot below:
-----------------------------------------

![Screenshot 2021-09-16 at 6 01 45 PM](https://user-images.githubusercontent.com/69039695/133614855-773f71fd-30a5-428d-83d1-64e20928ea00.png)
![Screenshot 2021-09-16 at 6 01 32 PM](https://user-images.githubusercontent.com/69039695/133614883-6c1f9ed2-1b8e-4e73-a274-f5d7ffdde951.png)
![Screenshot 2021-09-16 at 6 01 14 PM](https://user-images.githubusercontent.com/69039695/133614890-53f07fba-de44-4fc0-a734-666cfca07fa0.png)
![Screenshot 2021-09-16 at 6 00 32 PM](https://user-images.githubusercontent.com/69039695/133614892-bbb47b83-a1b8-4c20-95ea-101d298d1f75.png)
![Screenshot 2021-09-16 at 6 00 17 PM](https://user-images.githubusercontent.com/69039695/133614896-f908776d-33ab-4c74-9e95-91363ea67cb6.png)
![Screenshot 2021-09-16 at 5 58 54 PM](https://user-images.githubusercontent.com/69039695/133614897-90187b09-a96a-42b9-8342-7ebe0fa22048.png)
![Screenshot 2021-09-16 at 5 58 04 PM](https://user-images.githubusercontent.com/69039695/133614901-a2d1db3c-8f0b-4214-9667-4c321bb28ea7.png)
![Screenshot 2021-09-16 at 5 56 03 PM](https://user-images.githubusercontent.com/69039695/133614905-39023afa-de46-4ffa-9a22-adfd313bd4cc.png)
![Screenshot 2021-09-16 at 5 55 46 PM](https://user-images.githubusercontent.com/69039695/133614909-8353b4b7-8713-4958-88f5-028c7f78d7f2.png)
![Screenshot 2021-09-16 at 5 51 31 PM](https://user-images.githubusercontent.com/69039695/133614912-757e04e5-c8e3-4cdc-b53d-046efbb945cf.png)
![Screenshot 2021-09-16 at 5 51 11 PM](https://user-images.githubusercontent.com/69039695/133614914-7cf13ee9-71dc-4027-91fc-93e69ca88f19.png)
![Screenshot 2021-09-16 at 5 50 37 PM](https://user-images.githubusercontent.com/69039695/133614915-ee21ca0f-bd3f-4a35-ad7b-2e68b5f5ae9a.png)

**Comment by SonicDMG** [comment]
Hi there Bhaskar, thank you for your submission. Don't forget to complete step 2 of the homework and insert a custom show or genre of your choice.
2. Insert (mutate) a show or genre of your choice in the database.

Once complete please provide a screenshot.

**Comment by pal-bhaskar** [comment]
Hi @SonicDMG ,

Thank you for checking on this.
Please find attached screenshot for Step#2.
![Screenshot 2021-09-20 at 7 49 03 PM](https://user-images.githubusercontent.com/69039695/134018768-1156f809-aaef-4058-9437-8e390a5c9ce7.png)

**Comment by HadesArchitect** [comment]
Hey **Bhaskar Pal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/OS7fspE-QDSKFjrBFGDZCQ

**Comment by SonicDMG** [comment]
All looks good Bhaskar, thank you for following up.

**Comment by pal-bhaskar** [comment]
Thank you !!
