### ISSUE TITLE
[HW] Thiago Marsal Farias

### ISSUE THREAD

**Issue by thiagomarsal** [datastaxdevs/workshop-intro-to-graphql#65]
**Name:** Thiago Marsal Farias
**Email:** thiagomarsal.farias@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/thiago-marsal-farias/

Attach the homework screenshot below:
-----------------------------------------

![screencapture-8888-beige-cod-pks7w7qh-ws-us15-gitpod-io-2021-09-16-14_03_27](https://user-images.githubusercontent.com/8714453/133678412-f7f38fc1-35c1-47f9-942e-98aa54ba4c31.png)

**Comment by SonicDMG** [comment]
Hi there Thiago, thank you for your submission. Don't forget to complete step 2 of the homework and insert a custom show or genre of your choice.
2. Insert (mutate) a show or genre of your choice in the database.

Once complete please provide a screenshot.

**Comment by thiagomarsal** [comment]
Item 2: Insert a show into DB is completed:

![image](https://user-images.githubusercontent.com/8714453/134202661-fd0e1a81-443c-45ae-847e-7c8c4e1672a3.png)

**Comment by HadesArchitect** [comment]
Hey **Thiago Marsal Farias**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/74Wx5867RDahNXtFjfSqlA
