### ISSUE TITLE
[HW] Murad Dashdamirov

### ISSUE THREAD

**Issue by Murad-olen** [datastaxdevs/workshop-intro-to-graphql#79]
**Name:** Murad_Dashdamirov
**Email:** dashdamirov.olen2008@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/murad-dashdamirov-075a5b21b/

Attach the homework screenshot below:
-----------------------------------------

![Screenshot_139](https://user-images.githubusercontent.com/68665501/134577996-99a229a4-a4d5-49b5-b858-6f379feeea42.png)
![Screenshot_140](https://user-images.githubusercontent.com/68665501/134578016-3c1e4207-8265-4716-b204-7e41c67289aa.png)
![Screenshot_141](https://user-images.githubusercontent.com/68665501/134578033-7670ad1e-bf30-4fa6-85ba-80d40e892d6f.png)

**Comment by HadesArchitect** [comment]
Hey **Murad_Dashdamirov**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Bop7x8pDR-O80Ai0HDG0TQ
